//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nrprap
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tДейтсвие.
    /// </summary>
    // *** Start programmer edit section *** (tДейтсвие CustomAttributes)

    // *** End programmer edit section *** (tДейтсвие CustomAttributes)
    public enum tДейтсвие
    {
        
        // *** Start programmer edit section *** (tДейтсвие.Установка CustomAttributes)

        // *** End programmer edit section *** (tДейтсвие.Установка CustomAttributes)
        Установка,
        
        // *** Start programmer edit section *** (tДейтсвие.Прием CustomAttributes)

        // *** End programmer edit section *** (tДейтсвие.Прием CustomAttributes)
        Прием,
    }
}
