//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nrprap
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс.
    /// </summary>
    // *** Start programmer edit section *** (Класс CustomAttributes)

    // *** End programmer edit section *** (Класс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассE", new string[] {
            "Номер as \'Номер\'"})]
    [View("КлассL", new string[] {
            "Номер as \'Номер\'"})]
    public class Класс : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Nrprap.tДейтсвие fДействия;
        
        // *** Start programmer edit section *** (Класс CustomMembers)

        // *** End programmer edit section *** (Класс CustomMembers)

        
        /// <summary>
        /// Действия.
        /// </summary>
        // *** Start programmer edit section *** (Класс.Действия CustomAttributes)

        // *** End programmer edit section *** (Класс.Действия CustomAttributes)
        public virtual IIS.Nrprap.tДейтсвие Действия
        {
            get
            {
                // *** Start programmer edit section *** (Класс.Действия Get start)

                // *** End programmer edit section *** (Класс.Действия Get start)
                IIS.Nrprap.tДейтсвие result = this.fДействия;
                // *** Start programmer edit section *** (Класс.Действия Get end)

                // *** End programmer edit section *** (Класс.Действия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Класс.Действия Set start)

                // *** End programmer edit section *** (Класс.Действия Set start)
                this.fДействия = value;
                // *** Start programmer edit section *** (Класс.Действия Set end)

                // *** End programmer edit section *** (Класс.Действия Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Класс.Номер CustomAttributes)

        // *** End programmer edit section *** (Класс.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Класс.Номер Get start)

                // *** End programmer edit section *** (Класс.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Класс.Номер Get end)

                // *** End programmer edit section *** (Класс.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Класс.Номер Set start)

                // *** End programmer edit section *** (Класс.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Класс.Номер Set end)

                // *** End programmer edit section *** (Класс.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассE", typeof(IIS.Nrprap.Класс));
                }
            }
            
            /// <summary>
            /// "КлассL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассL", typeof(IIS.Nrprap.Класс));
                }
            }
        }
    }
}
