//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Nrprap
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прикол.
    /// </summary>
    // *** Start programmer edit section *** (Прикол CustomAttributes)

    // *** End programmer edit section *** (Прикол CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриколE", new string[] {
            "Строка as \'Строка\'",
            "Класс as \'Класс\'",
            "Класс.Номер as \'Номер\'"}, Hidden=new string[] {
            "Класс.Номер"})]
    [MasterViewDefineAttribute("ПриколE", "Класс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ПриколL", new string[] {
            "Строка as \'Строка\'",
            "Класс.Номер as \'Номер\'"})]
    public class Прикол : ICSSoft.STORMNET.DataObject
    {
        
        private string fСтрока;
        
        private IIS.Nrprap.Класс fКласс;
        
        // *** Start programmer edit section *** (Прикол CustomMembers)

        // *** End programmer edit section *** (Прикол CustomMembers)

        
        /// <summary>
        /// Строка.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.Строка CustomAttributes)

        // *** End programmer edit section *** (Прикол.Строка CustomAttributes)
        [StrLen(255)]
        public virtual string Строка
        {
            get
            {
                // *** Start programmer edit section *** (Прикол.Строка Get start)

                // *** End programmer edit section *** (Прикол.Строка Get start)
                string result = this.fСтрока;
                // *** Start programmer edit section *** (Прикол.Строка Get end)

                // *** End programmer edit section *** (Прикол.Строка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прикол.Строка Set start)

                // *** End programmer edit section *** (Прикол.Строка Set start)
                this.fСтрока = value;
                // *** Start programmer edit section *** (Прикол.Строка Set end)

                // *** End programmer edit section *** (Прикол.Строка Set end)
            }
        }
        
        /// <summary>
        /// Прикол.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.Класс CustomAttributes)

        // *** End programmer edit section *** (Прикол.Класс CustomAttributes)
        [PropertyStorage(new string[] {
                "Класс"})]
        [NotNull()]
        public virtual IIS.Nrprap.Класс Класс
        {
            get
            {
                // *** Start programmer edit section *** (Прикол.Класс Get start)

                // *** End programmer edit section *** (Прикол.Класс Get start)
                IIS.Nrprap.Класс result = this.fКласс;
                // *** Start programmer edit section *** (Прикол.Класс Get end)

                // *** End programmer edit section *** (Прикол.Класс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прикол.Класс Set start)

                // *** End programmer edit section *** (Прикол.Класс Set start)
                this.fКласс = value;
                // *** Start programmer edit section *** (Прикол.Класс Set end)

                // *** End programmer edit section *** (Прикол.Класс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриколE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриколE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриколE", typeof(IIS.Nrprap.Прикол));
                }
            }
            
            /// <summary>
            /// "ПриколL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриколL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриколL", typeof(IIS.Nrprap.Прикол));
                }
            }
        }
    }
}
